#!/bin/zsh

alias b="bash"
alias i='sudo'
alias e="touch"
alias m="mkdir"
alias v="$EDITOR ."
alias so="source"
alias cl='clear'
alias c='clear'
alias wd="pwd"
alias sx="startx"
alias kx="killall xinit"
alias is='sudo su'
alias nv="$EDITOR"
alias lh="ls -a"
alias loc="locate"
alias cdd="cd -"
alias rmf="rm -r"
alias cpf="cp -r"
alias irm="sudo rm"
alias icp="sudo cp"
alias imv="sudo mv"
alias irmf="sudo rm -r"
alias icpf="sudo cp -r"
alias imvf="sudo mv"
alias lsl="ls -l"
alias crole='sudo -iu'
alias a="$EDITOR ~/.config/zsh/aliases"
alias xn="$EDITOR ~/.config/x11/xprofile"
alias xr="$EDITOR ~/.config/x11/xresources"
alias cdbin="cd ~/.local/bin"
alias zs='source ~/.zshrc'
alias zc="$EDITOR ~/.zshrc"
alias nvc="$EDITOR config.h"
alias nvz="$EDITOR ~/.zsh_history"
alias nvi="$EDITOR init.lua"
alias nvr="$EDITOR --noplugin"
alias imi="sudo make install"
alias imci="sudo make clean install"
alias swap="cat /proc/sys/vm/swappiness"
alias rnscd="systemctl restart nscd"
alias brx='xrandr --output eDP-1 --brightness'
alias uadd='sudo usermod -aG'
alias clocale="dpkg-reconfigure locales"
alias imodem="systemctl start ModemManager.service"

# Programs
alias vc="$EDITOR ~/.config/nvim/init.lua"
alias lc="$EDITOR ~/.config/nvim/lua/core/init.lua"
alias al="$EDITOR ~/.config/alacritty/alacritty.yml"
alias fm="firefox -ProfileManager"
alias ipsql="systemctl start postgresql"
alias iredis="sudo /etc/init.d/redis_6379 start"
alias cdnm="/home/razak/.asdf/installs/nodejs/15.5.1/.npm/lib/node_modules"
alias codium="sudo nvim /usr/share/vscodium-bin/resources/app/product.json"

# Docker and Docker Compose
alias idocker="systemctl start docker.service"
alias dc="docker-compose"
alias dce="docker-compose exec"
alias dci="docker-compose up"
alias dcd="docker-compose down -v"
alias juiceshop='docker run --rm -p 3000:3000 bkimminich/juice-shop'

# Git
alias gp='git add . && git commit -m "auto push" && git push'
alias conf='/usr/bin/git --git-dir=$HOME/.dots/dotfiles/ --work-tree=$HOME'
alias nconf='/usr/bin/git --git-dir=$HOME/.dots/$EDITOR/ --work-tree=$HOME/.config/$EDITOR'

# Nord VPN
alias inord="systemctl start nordvpnd.service"
alias vn="nordvpn"
alias cvn="nordvpn connect"
alias dvn="nordvpn disconnect"
alias svn="nordvpn status"
alias me="curl icanhazip.com/"
alias alive="ping google.com"

# Ranger
alias f="ranger"
alias rc='ranger ~/.config'
alias rnv='ranger ~/.config/nvim'

# Pacman
alias Qi="pacman -Qi"
alias Ql="pacman -Ql"
alias wp='pacman -Qs'
alias p='sudo pacman -S'
alias r='sudo pacman -Rs'
alias y='yay -S'
alias upd='sudo pacman -Syu'
alias rcache="sudo pacman -Sc"

# Tmux
alias xm="tmux -L Main"
alias xd="tmuxd"
alias xb="tmuxb"
alias xsp="tmux display -p '#{socket_path}'"
alias xls="tmux ls"
alias nx='tmux n -s'
alias ax='tmux a -t'
alias axd='tmux -L Main a -t'
alias xc="$EDITOR ~/.config/tmux/tmux.conf"

# Misc
alias rfonts='fc-cache -vf ~/.local/share/fonts/'
alias remfonts='fc-cache -f -v'
alias plague='curl https://corona-stats.online/states/us'
alias lg='lazygit'
alias list_systemctl="systemctl list-unit-files --state=enabled"

# Bookmarks
# Ex: wr evaluates to the absolute path to your user's home directory.
export wr=~/Dev/
export cc=~/Dev/Code
export co=~/.config
export mo=~/.mozilla/firefox/profiles
export nca=~/.cache/nvim
export nsh=~/.local/share/nvim
export pack=~/.local/share/nvim/site/pack/packer
export ut=~/Dev/Code/m_
export doc=~/Documents
export docs=~/docs
export dots=~/.dots
export skl=~/.dots/suckless
export dw=~/Downloads
export nv=~/.config/nvim
export za=/run/media/razak/3E83258C04A90A32

alias cdwr='cd "$wr"'
alias cdcc='cd "$cc"'
alias cdco='cd "$co"'
alias cdmo='cd "$mo"'
alias cdnca='cd "$nca"'
alias cdnsh='cd "$nsh"'
alias cdpack='cd "$pack"'
alias cdut='cd "$ut"'
alias cdoc='cd "$doc"'
alias cdocs='cd "$docs"'
alias cdots='cd "$dots"'
alias cdskl='cd "$skl"'
alias cddw='cd "$dw"'
alias cdnv='cd "$nv"'
alias cdza='cd "$za"'
alias cdasdf='cd "$ASDF_INSTALLS"'
