#!/bin/zsh

alias b="bash"
alias d="dirs -v"
for index ({1..17}) alias "$index"="cd +${index}"; unset index
alias i='sudo'
alias e="touch"
alias m="mkdir"
alias obd="objdump -d"
alias so="source"
alias cl='clear'
alias c='clear'
alias wd="pwd"
alias sx="startx"
alias kx="killall xinit"
alias is='sudo su'
alias lh="ls -a"
alias loc="locate"
alias cdd="cd -"
alias rmf="rm -r"
alias cpf="cp -r"
alias irm="sudo rm"
alias icp="sudo cp"
alias imv="sudo mv"
alias irmf="sudo rm -r"
alias icpf="sudo cp -r"
alias imvf="sudo mv"
alias lsl="ls -l"
alias crole='sudo -iu'
alias zs='source ~/.config/zsh/.zshrc'
alias imi="sudo make install"
alias imci="sudo make clean install"
alias swap="cat /proc/sys/vm/swappiness"
alias rnscd="systemctl restart nscd"
alias brx='xrandr --output eDP-1 --brightness'
alias uadd='sudo usermod -aG'
alias clocale="dpkg-reconfigure locales"
alias imodem="systemctl start ModemManager.service"
# alias wifi="nmtui"
alias nscan="iwlist scanning"

# editor
alias v="$EDITOR ./"
alias nv=nvimProfiling
alias vim="nvim"
alias nvr=nvimRawProfiling

alias a="nvr ~/.config/zsh/aliases"
alias lc="nv ~/.config/nvim/lua/core/init.lua"
alias vc="nv ~/.config/nvim/init.lua"
alias al="nv ~/.config/alacritty/alacritty.yml"
alias zc="nvr ~/.config/zsh/.zshrc"
alias ze="nvr ~/.config/shell/profile"
alias xe="nvr ~/.config/x11/xprofile"
alias xr="nvr ~/.config/x11/xresources"
alias xR="nvr ~/.Xresources"
alias xc="nvr ~/.config/tmux/xd.tmux.conf"
alias xn="nvr ~/.config/x11/xinitrc"
alias nvi="nv init.lua"
alias nvc="nvr config.h"
alias nvz="nvr ~/.zsh_history"
alias nvv="nvr ~/docs/vim.log"
alias nvli="nv lua/core/init.lua"

# Programs
alias fm="firefox -ProfileManager"
alias ipsql="systemctl start postgresql"
alias iredis="sudo /etc/init.d/redis_6379 start"
alias codium="sudo nvim /usr/share/vscodium-bin/resources/app/product.json"
alias py="python"
alias xi="tuxi"
alias aw="toilet"
alias igp="sudo gparted"
alias vsc="vscodium ."

# Docker and Docker Compose
alias idocker="systemctl start docker.service"
alias dc="docker-compose"
alias dce="docker-compose exec"
alias dci="docker-compose up"
alias dcd="docker-compose down -v"
alias juiceshop='docker run --rm -p 3000:3000 bkimminich/juice-shop'

# Git
alias gp='git add . && git commit -m "updates" && git push'
alias conf='/usr/bin/git --git-dir=$HOME/.dots/dotfiles/ --work-tree=$HOME'
alias nconf='/usr/bin/git --git-dir=$HOME/.dots/$EDITOR/ --work-tree=$HOME/.config/$EDITOR'
alias confs="iconf -cs"
alias confa="iconf -csa"
alias confc="iconf -ccoms"
alias nconfs="iconf -ncs"
alias nconfa="iconf -ncsa"
alias nconfc="iconf -nccoms"
alias ccom="iconf -ccom"
alias nccom="iconf -nccom"
alias ccomall="iconf -ccomall"
alias nccomall="iconf -nccomall"
alias confe="iconf -cp"
alias nconfe="iconf -ncp"
alias nckm="nconf checkout main"
alias ncko="nconf checkout old"
alias ncks="nconf checkout slides"
alias nckt="nconf checkout test"
alias nckv="nconf checkout vscode"

# Nord VPN
alias inord="systemctl start nordvpnd.service"
alias vn="nordvpn"
alias cvn="nordvpn connect"
alias dvn="nordvpn disconnect"
alias svn="nordvpn status"
alias me="curl icanhazip.com/"
alias alive="ping google.com"

# Ranger
alias f="ranger"
alias rc='ranger ~/.config'
alias rnv='ranger ~/.config/nvim'

# Pacman
alias Qi="pacman -Qi"
alias Ql="pacman -Ql"
alias wp='pacman -Qs'
alias p='sudo pacman -S'
alias r='sudo pacman -Rs'
alias y='yay -Sy'
alias upd='sudo pacman -Syu'
alias rcache="sudo pacman -Sc"

# Tmux
alias xds="tmux -L Dev"
alias xbs="tmux -L Dull"
alias xd="tmuxd"
alias xb="tmuxb"
alias xsp="tmux display -p '#{socket_path}'"
alias xls="tmux ls"
alias nx='tmux -L Dev new -s'
alias ax='tmux a -t'
alias axd='tmux -L Dev a -t'
alias axb='tmux -L Dull a -t'
alias aff='ftmux -first'
alias fn='ftmux -s'
alias fk='ftmux -k'

# Misc
alias rfonts='fc-cache -vf ~/.local/share/fonts/'
alias remfonts='fc-cache -f -v'
alias plague='curl https://corona-stats.online/states/us'
alias lg='lazygit'
alias list_systemctl="systemctl list-unit-files --state=enabled"

# c@m
# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'
# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'
# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

mo=~/.mozilla/firefox/profiles
nca=~/.cache/nvim
doc=~/Documents
docs=~/docs
dots=~/.dots
skl=~/.dots/suckless
dw=~/Downloads
za=/run/media/razak/3E83258C04A90A32

alias cdbin="cd ~/.local/bin"
alias cdmo='cd "$mo"'
alias cdnca='cd "$nca"'
alias cdc='cd "$doc"'
alias cdcs='cd "$docs"'
alias cdts='cd "$dots"'
alias cdskl='cd "$skl"'
alias cddw='cd "$dw"'
alias cdza='cd "$za"'
alias cdwr='cd "$HOME/personal/workspace"'
alias cdcc='cd "$HOME/personal/workspace/coding"'
alias cdll='cd "$HOME/personal/workspace/coding/learn_something_new_everyday"'
alias cdco='cd "$XDG_CONFIG_HOME"'
alias cdnv='cd "$XDG_CONFIG_HOME/nvim"'
alias cdnsh='cd "$XDG_DATA_HOME/nvim"'
alias cdpack='cd "$XDG_DATA_HOME/nvim/site/pack/packer"'
alias cdusb1=' cd /run/media/razak/22B6-E52C/'
