#!/bin/sh

setopt RM_STAR_WAIT
setopt AUTOPARAMSLASH       # tab completing directory appends a slash
setopt ALWAYS_TO_END        # move cursor to end if word had one match
setopt AUTO_CD              # cd by typing directory name if it's not a command
setopt AUTO_LIST            # automatically list choices on ambiguous completion
setopt AUTO_MENU            # automatically use menu completion
setopt CORRECT_ALL          # autocorrect commands
setopt INTERACTIVE_COMMENTS # allow comments in interactive shells
setopt COMPLETE_ALIASES     # autocomplete for aliases
setopt APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS # remove older duplicate entries from history
setopt HIST_REDUCE_BLANKS   # remove superfluous blanks from history items
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY
setopt SHARE_HISTORY        # share history between different instances
setopt INC_APPEND_HISTORY   # save history entries as soon as they are entered
setopt No_BEEP              # beeping is annoying
setopt MENU_COMPLETE   # DO NOT AUTOSELECT THE FIRST COMPLETION ENTRY
setopt CD_ABLE_VARS
setopt EXTENDED_GLOB
unsetopt NOMATCH
unsetopt PROMPT_SP
unsetopt FLOWCONTROL
setopt COMPLETE_IN_WORD

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search

zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

zle_highlight=('paste:none')
zshcache_time="$(date +%s%N)"
