#!/bin/zsh
typeset -g -A key
typeset -U PATH path

setopt always_to_end        # move cursor to end if word had one match
setopt auto_cd              # cd by typing directory name if it's not a command
setopt auto_list            # automatically list choices on ambiguous completion
setopt auto_menu            # automatically use menu completion
setopt correct_all          # autocorrect commands

unsetopt nomatch
unsetopt PROMPT_SP


setopt append_history
setopt hist_ignore_all_dups # remove older duplicate entries from history
setopt hist_reduce_blanks   # remove superfluous blanks from history items
setopt inc_append_history   # save history entries as soon as they are entered
setopt share_history        # share history between different instances
setopt interactive_comments # allow comments in interactive shells
setopt complete_aliases     # autocomplete for aliases

