#!/bin/zsh

# PROMPT="%B%{$fg[blue]%}[%{$fg[white]%}%\r%{$fg[red]%}@%{$fg[white]%}%\m%{$fg[blue]%}]%{$reset_color%}%  %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
# PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%}'
# PROMPT+=' $(git_prompt_info)'

# # PROMPT="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

# ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg_bold[blue]%}(%{$fg[red]%}"
# ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
# ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[blue]%}) %{$fg[yellow]%}✗"
# ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg[blue]%})"

local return_code="%(?..%{$fg[red]%}%? ↵%{$reset_color%})"

# show up to 3 parent dirs, except ~, resolve all other dir aliases
function collapse_pwd {
    curr_pwd=$(pwd | sed -e "s,^$HOME,~,")
    relevant_slashes=$(expr $(echo $curr_pwd| tr -d -c /|wc -c) - 1)
    echo $curr_pwd| cut -d / -f$(($relevant_slashes>0?$relevant_slashes:1))-
}

PROMPT='%{${fg[green]}%}$(collapse_pwd) $(git_prompt_info)%{${fg_bold[blue]}%}»%{${reset_color}%} ' #${PWD/#$HOME/~}

RPS1="${return_code}"

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[yellow]%}‹"
ZSH_THEME_GIT_PROMPT_SUFFIX="› %{$reset_color%}"
