#!/bin/zsh

# clears the shell and displays the current dir
clear-ls-all() {
    clear
    exa -al
}
zle -N clear-ls-all


clear-tree-1() {
    clear
    tree -L 1
}
zle -N clear-tree-1

# clears the shell and displays the dir tree with level 2
clear-tree-2() {
    clear
    tree -L 2
}
zle -N clear-tree-2


# clears the shell and displays the dir tree with level 3
clear-tree-3() {
    clear
    tree -L 3
}
zle -N clear-tree-3


# prints the current date in ISO 8601
print-current-date() {
  LBUFFER+=$(date -I)
}
zle -N print-current-date

# prints the current Unix timestamp
print-unix-timestamp() {
  LBUFFER+=$(date +%s)
}
zle -N print-unix-timestamp

# appends the clipboard contents to the buffer
vi-append-clip-selection() {
  char=${RBUFFER:0:1}
  RBUFFER=${RBUFFER:1}
  RBUFFER=$char$(clippaste)$RBUFFER;
}
zle -N vi-append-clip-selection

# bindkey '^L' clear-ls-all
bindkey '^H' clear-tree-1
bindkey '^Y' clear-tree-2
bindkey '^J' clear-tree-3
bindkey '^D' print-current-date
# bindkey '^[^T' print-unix-timestamp
