# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export DEV_HOME="$HOME/personal/workspace/coding"
export DOTFILES="$HOME/.dots"
export RVIM_RUNTIME_DIR="$HOME/.local/share/rvim"
export RVIM_CONFIG_DIR="$HOME/.config/rvim"
export RVIM_CACHE_DIR="$HOME/.cache/rvim"
export ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"

export EDITOR="rvim"
export VISUAL="rvim"
export SUDO_EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="kitty"

# zsh config dir
export ZDOTDIR=$HOME/.config/zsh

export TEXT_EDITOR="nvim"

if which $TEXT_EDITOR >/dev/null; then
  export MANPAGER='less'
fi

# you may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# preferred editor for local and remote sessions
if [ -n "$NVIM_LISTEN_ADDRESS" ]; then
  export VISUAL="nvr -cc split --remote-wait +'set bufhidden=wipe'"
  export EDITOR="nvr -cc split --remote-wait +'set bufhidden=wipe'"
else
  export VISUAL=$TEXT_EDITOR
  export EDITOR=$TEXT_EDITOR
fi

export USE_EDITOR=$EDITOR

export GPG_TTY=$(tty)
export CLICOLOR=1
export SUDO_ASKPASS="$HOME/.local/bin/dmenu/dmenupass"

# Enable a better reverse search experience.
export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info --height=80% --color=dark --history=$HOME/.fzf_history"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND" # To apply to the command to CTRL-T as well
export FZF_TMUX=0 # Don't open FZF in a separate split in tmux

# History
export HIST_STAMPS="mm/dd/yyyy"
export HISTFILE=$ZSH_CACHE_DIR/.zsh_history
export HISTSIZE=50000
export SAVEHIST=50000

# Plugin Options & Configurations
export ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
export ZSH_AUTOSUGGEST_MANUAL_REBIND=""
export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=241'

# ignore params
export CORRECT_IGNORE="bin"
export CORRECT_IGNORE_FILE=".*"

export AUTO_NOTIFY_THRESHOLD=20
export AUTO_NOTIFY_EXPIRE_TIME=2000
