# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export DEV_HOME="$HOME/personal/workspace/coding"
export DOTFILES="$HOME/.dots"
export ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"

export SUDO_EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="kitty"
export IMAGE="sxiv"
export VIDEO="mpv"
export READER="zathura"
export COLORTERM="truecolor"
export OPENER="xdg-open"
export PAGER="less"
export MANPAGER="less"
export EDITOR="vi"
export VISUAL="vi"
export TEXT_EDITOR="vi"

if [[ $+commands[rvim] ]]; then
  export TEXT_EDITOR="rvim --no-lsp --no-ai"
elif [[ $+commands[pvim] ]]; then
  export TEXT_EDITOR="pvim"
elif [[ $+commands[nvim] ]]; then
  export TEXT_EDITOR="nvim"
elif [[ $+commands[vim] ]]; then
  export TEXT_EDITOR="vim"
fi

if which $TEXT_EDITOR >/dev/null; then
  export MANPAGER='less'
fi

# you may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export VISUAL=$TEXT_EDITOR
export EDITOR=$TEXT_EDITOR

export USE_EDITOR=$EDITOR

export GPG_TTY=$(tty)
export CLICOLOR=1
export SUDO_ASKPASS="$HOME/.local/bin/dmenu/dmenupass"

# zsh config dir
export ZDOTDIR=$HOME/.config/zsh

# Enable a better reverse search experience.
export FZF_TMUX_OPTS='-p80%,60%'
export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"
export FZF_DEFAULT_OPTS="--reverse \
--cycle \
--keep-right \
--bind=esc:abort \
--height 60% \
--border sharp \
--prompt '∷ ' \
--pointer ▶ "

# CTRL-/ to toggle small preview window to see the full command
# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

# History
export HIST_STAMPS="mm/dd/yyyy"
export HISTFILE=$ZSH_CACHE_DIR/.zsh_history
export HISTSIZE=500000
export SAVEHIST=500000

# Plugin Options & Configurations
export ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
export ZSH_AUTOSUGGEST_MANUAL_REBIND=""
export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=241'

# ignore params
export CORRECT_IGNORE="bin"
export CORRECT_IGNORE_FILE=".*"

export AUTO_NOTIFY_THRESHOLD=20
export AUTO_NOTIFY_EXPIRE_TIME=2000
