# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export DEV_HOME="$HOME/personal/workspace/coding"
export RVIM_RUNTIME_DIR="$HOME/.local/share/rvim"
export RVIM_CONFIG_DIR="$HOME/.config/rvim"
export RVIM_CACHE_DIR="$HOME/.cache/rvim"

export EDITOR="rvim"
export VISUAL="rvim"
export SUDO_EDITOR="nvim"
export BROWSER="firefox"
export TERMINAL="kitty"

# zsh config dir
export ZDOTDIR=$HOME/.config/zsh
