#!/bin/zsh

# profiling
zmodload zsh/zprof

# DO not highligh& pasted text
zle_highlight=('paste:none')

# colors
autoload -U colors && colors

# Local scripts
for script in $ZDOTDIR/scripts/*; do
  source $script
done

# These should be source *BEFORE* setting up hooks
add_plugin zsh-completions/zsh-completions.plugin.zsh
add_plugin zsh-autosuggestions/zsh-autosuggestions.zsh
add_plugin zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
add_plugin conda-zsh-completion/conda-zsh-completion.plugin.zsh
autoload zmv # builtin zsh rename command

# Load config files
add_files opts compe vim-mode hooks binds prompt aliases

# Plugins options
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_MANUAL_REBIND=""
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# asdf
if exists asdf; then
  fpath+="$ASDF_DIR/completions/"
fi

# fnm
if exists fnm; then
  eval "`fnm env`"
fi

# Azure cli
if exists az; then
  source $HOME/lib/azure-cli/az.completion
fi

# zoxide
if exists zoxide; then
  eval "$(zoxide init zsh)"
fi

# Load other completions
if [ -d "$ZDOTDIR/plugins" ]; then
  fpath+="$ZDOTDIR/completion/"
fi

# pip
# eval "`pip completion --zsh`"

# fzf
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

conda_init() {
  # >>> conda initialize >>>
  # !! Contents within this block are managed by 'conda init' !!
  __conda_setup="$('/home/razak/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
    eval "$__conda_setup"
  else
    if [ -f "/home/razak/miniconda3/etc/profile.d/conda.sh" ]; then
      . "/home/razak/miniconda3/etc/profile.d/conda.sh"
    else
      export PATH="/home/razak/miniconda3/bin:$PATH"
    fi
  fi
  unset __conda_setup
  # <<< conda initialize <<<
}
# conda_init

# Load and initialize the completion system ignoring insecure directories with a
# cache time of 20 hours, so it should almost always regenerate the first time a
# shell is opened each day.
# #q expands globs in conditional expressions
_comp_path="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
if [[ $_comp_path(#qNmh-20) ]]; then
  # -C (skip function check) implies -i (skip security check).
  compinit -C -d "$_comp_path"
else
  mkdir -p "$_comp_path:h"
  compinit -i -d "$_comp_path"
  # Keep $_comp_path younger than cache time even if it isn't regenerated.
  touch "$_comp_path"
fi
unset _comp_path
