#!/bin/zsh

# profiling
zmodload zsh/zprof

# DO not highligh& pasted text
zle_highlight=('paste:none')

# colors
autoload -U colors && colors

# ignore params
CORRECT_IGNORE="bin"
CORRECT_IGNORE_FILE=".*"

#-------------------------------------------------------------------------------
#   LOCAL SCRIPTS
#-------------------------------------------------------------------------------
for script in $ZDOTDIR/scripts/*; do
  source $script
done

#-------------------------------------------------------------------------------
#           Plugins
#-------------------------------------------------------------------------------
# These should be source *BEFORE* setting up hooks
add_plugin 'zsh-completions'
add_plugin 'zsh-autosuggestions'
add_plugin 'zsh-syntax-highlighting'
add_plugin 'zsh-hist'
add_plugin 'zsh-autopair'
add_completion 'conda-zsh-completion' false
add_completion 'fnm'
autoload zmv # builtin zsh rename command

#-------------------------------------------------------------------------------
#               Modules
#-------------------------------------------------------------------------------
add_modules opts compe hooks binds vim-mode vcs prompt aliases
add_plugin 'git' # Needs to be here b/c it requires compdef (compe)

#-------------------------------------------------------------------------------
#               Configurations
#-------------------------------------------------------------------------------
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_MANUAL_REBIND=""
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# fzf
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# asdf
if exists asdf; then
  fpath+="$ASDF_DIR/completions/"
fi

# fnm
if exists fnm; then
  eval "`fnm env`"
fi

# zoxide
if exists zoxide; then
  eval "$(zoxide init zsh)"
fi

# Azure cli
if exists az; then
  source $HOME/lib/azure-cli/az.completion
fi

# Azure cli
if [[ -e "$HOME/.cargo/env" ]]; then
  source "$HOME/.cargo/env"
fi

# conda_init and pip
conda_init false

# pyenv init
pyenv_init false

export CODELLDB='$HOME/.vscode-oss/extensions/vadimcn.vscode-lldb-1.7.0'

path=(
  "$CODELLDB/adapter/"
  "$CODELLDB/lldb/bin"
  "$path[@]"
)

export PATH
