#!/bin/zsh

# Init completions
autoload -Uz compinit
zmodload -i zsh/complist
_comp_options+=(globdots)   # Include hidden files.
compinit

# profiling
zmodload zsh/zprof

# DO not highligh& pasted text
zle_highlight=('paste:none')

# colors
autoload -U colors && colors

# ignore params
CORRECT_IGNORE="bin"
CORRECT_IGNORE_FILE=".*"

#-------------------------------------------------------------------------------
#   LOCAL SCRIPTS
#-------------------------------------------------------------------------------
for script in $ZDOTDIR/scripts/*; do
  source $script
done

#-------------------------------------------------------------------------------
#           Plugins
#-------------------------------------------------------------------------------
# These should be source *BEFORE* setting up hooks
add_plugin 'zsh-completions'
add_plugin 'zsh-autosuggestions'
add_plugin 'zsh-syntax-highlighting'
add_plugin 'zsh-hist'
add_plugin 'git'
add_completion 'conda-zsh-completion' false
add_completion 'fnm'
autoload zmv # builtin zsh rename command

#-------------------------------------------------------------------------------
#               Modules
#-------------------------------------------------------------------------------
add_modules opts compe vim-mode hooks binds vcs prompt aliases

#-------------------------------------------------------------------------------
#               Configurations
#-------------------------------------------------------------------------------
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_MANUAL_REBIND=""
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# fzf
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# asdf
if exists asdf; then
  fpath+="$ASDF_DIR/completions/"
fi

# fnm
if exists fnm; then
  eval "`fnm env`"
fi

# zoxide
if exists zoxide; then
  eval "$(zoxide init zsh)"
fi

# Azure cli
if exists az; then
  source $HOME/lib/azure-cli/az.completion
fi

# Azure cli
if exists cargo; then
  source "$HOME/.cargo/env"
fi

# conda_init and pip
conda_init false

autoload -U add-zsh-hook
add-zsh-hook chpwd python_env
python_env

# Load and initialize the completion system ignoring insecure directories with a
# cache time of 20 hours, so it should almost always regenerate the first time a
# shell is opened each day.
# #q expands globs in conditional expressions
_comp_path="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
if [[ $_comp_path(#qNmh-20) ]]; then
  # -C (skip function check) implies -i (skip security check).
  compinit -C -d "$_comp_path"
else
  mkdir -p "$_comp_path:h"
  compinit -i -d "$_comp_path"
  # Keep $_comp_path younger than cache time even if it isn't regenerated.
  touch "$_comp_path"
fi
unset _comp_path
