#!/bin/zsh

typeset -U PATH path

LOCAL="$HOME/.local/bin"
path+=(
  "$LOCAL"
  "$LOCAL/dmenu"
  "$LOCAL/dwm"
  "$LOCAL/sb"
  "$LOCAL/statusbar"
  "$LOCAL/startup"
  "$LOCAL/utils"
)

# fzf
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# g - go version manager
export GOPATH="$HOME/go";
export GOROOT="$HOME/.go";
path+=(
  "$GOPATH/bin"
)

# YARN
if [ -d "$HOME/.yarn/bin" ]; then
  export YARNPATH="$HOME/.yarn/bin"
  path+=(
    "$YARNPATH"
  )
fi

# Deta cli
if [ -e "$HOME/.deta/bin/deta" ]; then
  export DETA_HOME="$HOME/.deta"
  path+=(
  "$DETA_HOME/bin"
  )
fi

export PATH
