#!/bin/zsh

typeset -U PATH path

# ssh
# eval "$(ssh-agent -s)"
# ssh-add ~/.ssh/id_rsa_razak17

LOCAL="$HOME/.local/bin"
path+=(
  "$LOCAL"
  "$LOCAL/dmenu"
  "$LOCAL/dwm"
  "$LOCAL/sb"
  "$LOCAL/statusbar"
  "$LOCAL/startup"
  "$LOCAL/utils"
)

# fzf
if [[ -x "$HOME/.fzf/bin/fzf" ]]; then
  path+=("$HOME/.fzf/bin")
fi

# java
export JAVA_HOME="/usr/lib/jvm/java-26-openjdk";

# Go user binaries
export GOPATH="$HOME/go"
path+=(
  "$GOPATH/bin"
)

# Fly
if [ -e "$HOME/.fly/bin/fly" ]; then
  export FLYCTL_INSTALL="$HOME/.fly"
  path+=(
  "$FLYCTL_INSTALL/bin"
  )
fi

# Turso
if [ -e "$HOME/.turso/turso" ]; then
  export TURSO_INSTALL="$HOME/.turso/"
  path+=(
  "$TURSO_INSTALL"
  )
fi

# Cargo user binaries
if [ -e "$HOME/.cargo" ]; then
  path+=(
  "$HOME/.cargo/bin"
  )
fi

# duckdb
if [ -f "$HOME/.duckdb/cli/latest/duckdb" ]; then
  export DUCK_DB="$HOME/.duckdb/"
  path+=(
  "$DUCK_DB/cli/latest"
  )
fi

# opencode
if [ -e "$HOME/.opencode/bin/opencode" ]; then
  export OPENCODE_PATH="$HOME/.opencode/"
  path+=(
  "$OPENCODE_PATH/bin"
  )
fi

export PATH
