#!/bin/zsh

typeset -U PATH path

LOCAL="$HOME/.local/bin"
path+=(
  "$LOCAL"
  "$LOCAL/dmenu"
  "$LOCAL/dwm"
  "$LOCAL/sb"
  "$LOCAL/statusbar"
  "$LOCAL/startup"
  "$LOCAL/utils"
)

# fzf
[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh

# g - go version manager
export GOPATH="$HOME/go";
export GOROOT="$HOME/.go";
path+=(
  "$GOPATH/bin"
)

# fnm
if [ -e "$HOME/.local/share/fnm/fnm" ]; then
  export FNMDIR="$HOME/.local/share/fnm"
  path+=(
    "$FNMDIR"
  )
fi

# YARN
if [ -d "$HOME/.yarn/bin" ]; then
  export YARNPATH="$HOME/.yarn/bin"
  path+=(
    "$YARNPATH"
  )
fi

# DENO
if [ -e "$HOME/.deno/bin/deno" ]; then
  export DENO_INSTALL="$HOME/.deno"
  path+=(
    "$DENO_INSTALL/bin"
  )
fi

# Deta cli
if [ -e "$HOME/.detaspace/bin" ]; then
  export DETA_HOME="$HOME/.detaspace"
  path+=(
  "$DETA_HOME/bin"
  )
fi


# bun
if [ -d "$HOME/.bun" ]; then
  export BUN_INSTALL="$HOME/.bun"
  path+=(
  "$BUN_INSTALL/bin"
  )
fi

# pnpm
export PNPM_HOME="$HOME/.local/share/pnpm"
path+=(
"$PNPM_HOME"
)


# Fly
if [ -e "$HOME/.fly/bin/fly" ]; then
  export FLYCTL_INSTALL="$HOME/.fly"
  path+=(
  "$FLYCTL_INSTALL/bin"
  )
fi

# Turso
if [ -e "$HOME/.turso/turso" ]; then
  export TURSO_INSTALL="$HOME/.turso/"
  path+=(
  "$TURSO_INSTALL"
  )
fi

export PATH
