#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
  source "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
fi

while type dwm >/dev/null ; do
  dwm 2> ~/.dwm.log && continue || break ;
done

