#!/bin/sh

/usr/bin/xmodmap -e "clear mod5"

# Executed by startx (run your window manager from here)
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

[ -r "$HOME/.config/shell/environment.sh" ] && . "$HOME/.config/shell/environment.sh"

xprofile_start_once() {
	process_name=$1
	shift

	command -v "$1" >/dev/null 2>&1 || return 0
	pgrep -xu "$USER" -x "$process_name" >/dev/null 2>&1 && return 0
	"$@" &
}

xprofile_run() {
	command -v "$1" >/dev/null 2>&1 || return 0
	"$@" &
}

xprofile_start_once mpd mpd
xprofile_start_once clipmenud clipmenud
xprofile_start_once dunst dunst
xprofile_start_once redshift "$HOME/.local/bin/startup/st-brightness"
xprofile_start_once ibattery-notify "$HOME/.local/bin/startup/st-battery-notify"
xprofile_start_once picom picom
xprofile_start_once syncthing "$HOME/.local/bin/startup/st-syncthing"

xprofile_run "$HOME/.local/bin/startup/st-setbg" --fav
xprofile_run "$HOME/.local/bin/startup/st-keyboard"

unset process_name
unset -f xprofile_start_once xprofile_run
