#!/bin/zsh

function add_plugin() {
  for i in "$@"; do
    [ -f $ZDOTDIR/plugins/$i ] && source $ZDOTDIR/plugins/$i
  done
}

function add_files() {
  for i in "$@"; do
    [ -f $ZDOTDIR/$i ] && source $ZDOTDIR/$i
  done
}

prof="${XDG_CACHE_HOME:-$HOME/.cache}/nvim/prof.log"
function nvimProfiling() {
  if [ -z "$@" ]; then
    nvim --startuptime $prof
  else
    nvim "$@" --startuptime $prof
  fi
}

prof_raw="${XDG_CACHE_HOME:-$HOME/.cache}/nvim/prof_raw.log"
function nvimRawProfiling() {
  if [ -z "$@" ]; then
    nvim --noplugin -u ~/docs/raw.lua --startuptime $prof_raw
  else
    nvim --noplugin -u ~/docs/raw.lua "$@" --startuptime $prof_raw
  fi
}

# compress
function comp() {
  local DATE="$(date +%Y%m%d-%H%M%S)"
  tar cvzf "$DATE-$@.tar.gz" "$@"
}

function bak() {
  for file in "$@"; do
    cp "$file" "$file".bak
  done
}

function colours() {
  for i in {0..255}; do
    printf "\x1b[38;5;${i}m colour${i}"
    if (( $i % 5 == 0 )); then
      printf "\n"
    else
      printf "\t"
    fi
  done
}

function alive() {
  if ping -c 1 google.com; then
    echo "It appears you have a working internet connection"
  fi
}

function old() {
  if grep -q $@ ~/.zsh_history; then
    echo "You appear to have typed '$@' in the past."
  else
    echo "You haven't typed '$@' before."
  fi
}
