#!/bin/zsh

function conda_activate() {
  # >>> conda initialize >>>
  # !! Contents within this block are managed by 'conda init' !!
  __conda_setup="$('/home/razak/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
    eval "$__conda_setup"
  else
    if [ -f "/home/razak/miniconda3/etc/profile.d/conda.sh" ]; then
      . "/home/razak/miniconda3/etc/profile.d/conda.sh"
    else
      export PATH="/home/razak/miniconda3/bin:$PATH"
    fi
  fi
  unset __conda_setup
  # <<< conda initialize <<<
}

function pip_init() {
  eval "`pip completion --zsh`"
}

function conda_init() {
  if [ "$1" = false ] && return
  conda_activate
  add_completion 'conda-zsh-completion' true
  pip_init
}

function pyenv_init() {
  if [ "$1" = false ] && return
  if exists pyenv; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
    eval "$(pyenv init - --no-rehash zsh)"
  fi
}

function activate() {
  MYVENV=./venv
  MYDOTVENV=".venv"
  MYPIPENV=./Pipfile
  [[ -d $MYVENV ]] && source $MYVENV/bin/activate
  [[ -d $MYDOTVENV ]] && source $MYDOTVENV/bin/activate
  [[ -e $MYPIPENV ]] && pipenv shell
}

prof="${XDG_CACHE_HOME:-$HOME/.cache}/rvim/prof.log"
function rvimProfiling() {
  if [[ $+commands[rvim] ]]; then
    rvim "$@" --startuptime "$prof"
  fi
}

prof_raw="${XDG_CACHE_HOME:-$HOME/.cache}/rvim/prof_raw.log"
function nvimProfiling() {
  if [[ $+commands[nvim] ]]; then
    nvim "$@" --startuptime "$prof_raw"
  fi
}

# compress
function comp() {
  local DATE="$(date +%Y%m%d-%H%M%S)"
  tar cvzf "$DATE-$@.tar.gz" "$@"
}

function bak() {
  for file in "$@"; do
    cp "$file" "$file".bak
  done
}

function colours() {
  for i in {0..255}; do
    printf "\x1b[38;5;${i}m colour${i}"
    if (( $i % 5 == 0 )); then
      printf "\n"
    else
      printf "\t"
    fi
  done
}

function alive() {
  if ping -c 2 google.com; then
    # echo "It appears you have a working internet connection"
    notify-send "📶 Internet Status " "\- You are connected." -t 2000
  else
    notify-send "❎ Internet Status " "\- No internet connection." -t 2000
  fi
}

function old() {
  if grep -q $@ ~/.cache/zsh/.zsh_history; then
    echo "You appear to have typed '$@' in the past."
  else
    echo "You haven't typed '$@' before."
  fi
}
