#!/bin/zsh

function add_files() {
  for i in "$@"; do
    [ -f $ZDOTDIR/$i ] && source $ZDOTDIR/$i
  done
}

function add_plugin() {
  add_files "plugins/$1/$1.plugin.zsh" || add_file "plugins/$1/$1.zsh"
}

function add_completion() {
  if [ "$2" = false ] && return
  if [ -d "$ZDOTDIR/plugins/$1" ]; then
    dir="plugins"
    file_path=$(ls $ZDOTDIR/$dir/$1/_*)
  elif [ -d "$ZDOTDIR/completion/$1" ]; then
    dir="completion"
    file_path=$(ls $ZDOTDIR/$dir/$1/_*)
  else
    return
  fi
  fpath+="$(dirname "${file_path}")"
  # file="$(basename "${file_path}")"
  # compinit "${file:1}" _comp_path
}

function conda_activate() {
  # >>> conda initialize >>>
  # !! Contents within this block are managed by 'conda init' !!
  __conda_setup="$('/home/razak/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
    eval "$__conda_setup"
  else
    if [ -f "/home/razak/miniconda3/etc/profile.d/conda.sh" ]; then
      . "/home/razak/miniconda3/etc/profile.d/conda.sh"
    else
      export PATH="/home/razak/miniconda3/bin:$PATH"
    fi
  fi
  unset __conda_setup
  # <<< conda initialize <<<
}

function conda_init() {
  if [ "$1" = false ] && return
  conda_activate
}

prof="${XDG_CACHE_HOME:-$HOME/.cache}/nvim/prof.log"
function nvimProfiling() {
  if [ -z "$@" ]; then
    nvim --startuptime $prof
  else
    nvim "$@" --startuptime $prof
  fi
}

prof_raw="${XDG_CACHE_HOME:-$HOME/.cache}/nvim/prof_raw.log"
function nvimRawProfiling() {
  if [ -z "$@" ]; then
    nvim --noplugin -u ~/docs/raw.lua --startuptime $prof_raw
  else
    nvim --noplugin -u ~/docs/raw.lua "$@" --startuptime $prof_raw
  fi
}

# compress
function comp() {
  local DATE="$(date +%Y%m%d-%H%M%S)"
  tar cvzf "$DATE-$@.tar.gz" "$@"
}

function bak() {
  for file in "$@"; do
    cp "$file" "$file".bak
  done
}

function colours() {
  for i in {0..255}; do
    printf "\x1b[38;5;${i}m colour${i}"
    if (( $i % 5 == 0 )); then
      printf "\n"
    else
      printf "\t"
    fi
  done
}

function alive() {
  if ping -c 1 google.com; then
    echo "It appears you have a working internet connection"
  fi
}

function old() {
  if grep -q $@ ~/.zsh_history; then
    echo "You appear to have typed '$@' in the past."
  else
    echo "You haven't typed '$@' before."
  fi
}
