#!/bin/sh

# find files
ff() {
	file=$(fd . | fzf)
	if [[ -n $file ]]; then
		rvim $file
	fi
}

# zd - use zoxide & FZF to find and go to directory
# Not sure why zoxide query -i with FZF doesn't CD
zd() {
	dir=$(zoxide query -l | fzf)

	if [[ -n $dir ]]; then
		cde $dir || exit
	fi
}

# see environment variables
envs() {
	# ps eww -o command | tr ' ' '\n'
	printenv | fzf
}

# search notes and open it in nvim
vn() {
	note=$(fd . '/home/razak/notes/src' | fzf)
	if [[ -n $note ]]; then
		rvim $note
	fi
}

# tm irc it will attach to the irc session (if it exists), else it will create it.
# tm with one session open, it will attach to that session.
# tm with more than one session open it will let you select the session via fzf.
txd() {
	server="Dev"
	[[ -n "$TMUX" ]] && change="switch-client" || change="attach-session"
	if [ $1 ]; then
		tmux -L $server $change -t "$1" 2>/dev/null || (tmux -L $server new-session -d -s $1 && tmux -L $server $change -t "$1")
		return
	fi
	session=$(tmux -L $server list-sessions -F "#{session_name}" 2>/dev/null | fzf --exit-0) && tmux -L $server $change -t "$session" || echo "No sessions found."
}

# fs [FUZZY PATTERN] - Select selected tmux session
#   - Bypass fuzzy finder if there's only one match (--select-1)
#   - Exit if there's no match (--exit-0)
fs() {
	session=$(tmux -L Dev list-sessions -F "#{session_name}" | fzf --query="$1" --select-1 --exit-0)
  echo "$session"
	tmux -L Dev switch-client -t "$session"
}

# fe [FUZZY PATTERN] - Open the selected file with the default editor
#   - Bypass fuzzy finder if there's only one match (--select-1)
#   - Exit if there's no match (--exit-0)

fe() {
	IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0 --preview 'bat --color "always" {}' --preview-window=right:60%))
	[[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

fn() {
  pushd "$HOME/notes/src" > /dev/null || return
	IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0 --preview 'bat --color "always" {}' --preview-window=right:60%))
	[[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

fr() {
  pushd "$HOME/.config/rvim" > /dev/null || return
	IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0 --preview 'bat --color "always" {}' --preview-window=right:60%))
	[[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

fu() {
	IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0 --preview 'bat --color "always" {}' --preview-window=right:60%))
	[[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}

fz() {
  pushd "$ZDOTDIR" > /dev/null || return
	IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0 --preview 'bat --color "always" {}' --preview-window=right:60%))
	[[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}
