#!/usr/bin/env bash

# requires: https://github.com/razak17/ftmux

WORKSPACE="$HOME/personal/workspace"

checkSession() {
	if [[ $(ftmux -has "$1") == true ]]; then
		showWarning "$session"
		attachSession "$session"
		exit
	fi
}

showWarning() {
	notify-send "Session '$1' already exists." "Attaching ..." -t 1000
	# notify-send -u critical "Session '$@' already exists." "Aborting ..." -t 1000
}

attachSession() {
	tmux -L Dev attach-session -t "$session" 2>/dev/null
}

xrv() {
	session="rvim"

	checkSession "$session"

	ftmux -n "$session" "new" "$HOME/.config/rvim"
	ftmux -w "$session" "config" -c "$HOME/Downloads"

	# Get first window
	firstWindow=$(ftmux --session-win-id "$session" 0)
	firstPane=$(ftmux --window-pane-id "$firstWindow" 0)
	ftmux --split-pane -v -c "$HOME/docs" -t "$firstPane"

	# Get second window
	secondWindow=$(ftmux --session-win-id "$session" 1)
	firstPane=$(ftmux --window-pane-id "$secondWindow" 0)
	ftmux --split-pane -v -c "$HOME/Sync" -t "$firstPane"

	attachSession "$session"
}

om() {
	session="origin-media"
	repo="$WORKSPACE/rgt/Origin-Media"

	args="$*"
	send_keys=true

	if [[ $args == '--no-run' ]]; then
		send_keys=false
	fi

	checkSession "$session"

	ftmux -n "$session" "main" "$repo/om-admin"
	ftmux -w "$session" "api & core" -c "$repo/om-core"

	# admin
	firstWindow=$(ftmux --session-win-id "$session" 0)
	firstPane=$(ftmux --window-pane-id "$firstWindow" 0)
	ftmux --split-pane -v -c "$repo/om-admin" -t "$firstPane"
	secondPane=$(ftmux --window-pane-id "$firstWindow" 1)
	ftmux --split-pane -h -c "$repo/om-api" -t "$secondPane"
	thirdPane=$(ftmux --window-pane-id "$firstWindow" 2)
	if [[ $send_keys == true ]]; then
		ftmux --send-keys "$firstPane" "rvim" "C-m"
		ftmux --send-keys "$secondPane" "npm run dev" "C-m"
		ftmux --send-keys "$thirdPane" "go run main.go local_dev" "C-m"
	fi

	# api
	secondWindow=$(ftmux --session-win-id "$session" 1)
	firstPane=$(ftmux --window-pane-id "$secondWindow" 0)
	ftmux --split-pane -v -c "$repo/om-api" -t "$firstPane"
}

om-old() {
	session="origin-media"
	repo="$WORKSPACE/rgt/Origin-Media"

	args="$*"
	send_keys=true

	if [[ $args == '--no-run' ]]; then
		send_keys=false
	fi

	checkSession "$session"

	ftmux -n "$session" "admin" "$repo/om-admin"
	ftmux -w "$session" "api" -c "$repo/om-api"
	ftmux -w "$session" "core" -c "$repo/om-core"

	# admin
	firstWindow=$(ftmux --session-win-id "$session" 0)
	firstPane=$(ftmux --window-pane-id "$firstWindow" 0)
	ftmux --split-pane -v -c "$repo/om-admin" -t "$firstPane"
	secondPane=$(ftmux --window-pane-id "$firstWindow" 1)
	if [[ $send_keys == true ]]; then
		ftmux --send-keys "$firstPane" "rvim" "C-m"
		ftmux --send-keys "$secondPane" "npm run dev" "C-m"
	fi

	# api
	secondWindow=$(ftmux --session-win-id "$session" 1)
	firstPane=$(ftmux --window-pane-id "$secondWindow" 0)
	ftmux --split-pane -v -c "$repo/om-api" -t "$firstPane"
	secondPane=$(ftmux --window-pane-id "$secondWindow" 1)
	if [[ $send_keys == true ]]; then
		# ftmux --send-keys "$firstPane" "rvim --no-lsp" "C-m"
		ftmux --send-keys "$secondPane" "go run main.go local_dev" "C-m"
	fi

	# core
	thirdWindow=$(ftmux --session-win-id "$session" 2)
	firstPane=$(ftmux --window-pane-id "$thirdWindow" 0)
	ftmux --split-pane -v -c "$repo/om-core" -t "$firstPane"
	# if [[ $send_keys == true ]]; then
	# 	ftmux --send-keys "$firstPane" "rvim --no-lsp" "C-m"
	# fi
}

coa() {
	session="coa-nodejs-api"
	repo="$WORKSPACE/coding/interview/coa/nodejs-api-app"

	checkSession "$session"

	ftmux -n "$session" "api" "$repo"
	ftmux -w "$session" "run" -c "$repo"

	# api
	firstWindow=$(ftmux --session-win-id "$session" 0)
	firstPane=$(ftmux --window-pane-id "$firstWindow" 0)
	ftmux --split-pane -v -c "$WORKSPACE/coding/portfolio/youtube-clone/youtube-clone-backend" -t "$firstPane"

	# run
	secondWindow=$(ftmux --session-win-id "$session" 1)
	firstPane=$(ftmux --window-pane-id "$secondWindow" 0)
	ftmux --split-pane -v -c "$repo" -t "$firstPane"
	ftmux --send-keys "$firstPane" "yarn dev" "C-m"
}

jesse() {
	session="jesse"
	repo="$WORKSPACE/rgt/jesse/proj-jesse-ai-agent"
	ui="$WORKSPACE/rgt/jesse/jesse-dashboard"
	args="$*"
	send_keys=true

	if [[ $args == '--no-run' ]]; then
		send_keys=false
	fi

	checkSession "$session"

	ftmux -n "$session" "services" "$repo"
	ftmux -w "$session" "ui" -c "$ui"

	# admin
	firstWindow=$(ftmux --session-win-id "$session" 0)
	firstPane=$(ftmux --window-pane-id "$firstWindow" 0)
	ftmux --send-keys "$firstPane" "source env/bin/activate" "C-m"
	ftmux --split-pane -v -c "$repo" -t "$firstPane"
	secondPane=$(ftmux --window-pane-id "$firstWindow" 1)
	ftmux --send-keys "$secondPane" "source env/bin/activate" "C-m"
	if [[ $send_keys == true ]]; then
		ftmux --send-keys "$firstPane" "rvim" "C-m"
		ftmux --send-keys "$secondPane" "uvicorn api.main:app --reload" "C-m"
	fi

	secondWindow=$(ftmux --session-win-id "$session" 1)
	firstPane=$(ftmux --window-pane-id "$secondWindow" 0)
	ftmux --split-pane -v -c "$ui" -t "$firstPane"
	secondPane=$(ftmux --window-pane-id "$secondWindow" 1)
	if [[ $send_keys == true ]]; then
		ftmux --send-keys "$firstPane" "rvim" "C-m"
		ftmux --send-keys "$secondPane" "npm run dev" "C-m"
	fi

	attachSession "$session"
}

mediboard() {
	session="mediboard"
	repo="$WORKSPACE/rgt/mediboard"
	args="$*"
	send_keys=true

	if [[ $args == '--no-run' ]]; then
		send_keys=false
	fi

	checkSession "$session"

	ftmux -n "$session" "code" "$repo"
	ftmux -w "$session" "run" -c "$repo"

	# admin
	firstWindow=$(ftmux --session-win-id "$session" 0)
	firstPane=$(ftmux --window-pane-id "$firstWindow" 0)
	ftmux --split-pane -v -c "$repo" -t "$firstPane"
	if [[ $send_keys == true ]]; then
		ftmux --send-keys "$firstPane" "vai" "C-m"
	fi
	# secondPane=$(ftmux --window-pane-id "$firstWindow" 1)
	# if [[ $send_keys == true ]]; then
	# 	ftmux --send-keys "$secondPane" "v --no-lsp" "C-m"
	# fi
	# ftmux --send-keys "$secondPane" "\c mediboard3" "C-m"

	secondWindow=$(ftmux --session-win-id "$session" 1)
	firstPane=$(ftmux --window-pane-id "$secondWindow" 0)
	ftmux --split-pane -v -c "$repo" -t "$firstPane"
	secondPane=$(ftmux --window-pane-id "$secondWindow" 1)
	ftmux --send-keys "$firstPane" "fnm use v16.14.0" "C-m"
	ftmux --send-keys "$secondPane" "fnm use v16.14.0" "C-m"
	if [[ $send_keys == true ]]; then
		ftmux --send-keys "$firstPane" "yarn start:server" "C-m"
		ftmux --send-keys "$secondPane" "yarn start:client" "C-m"
	fi

	attachSession "$session"
}

jesse-old() {
	session="jesse"
	repo="$WORKSPACE/rgt/jesse"

	args="$*"
	send_keys=true

	if [[ $args == '--no-run' ]]; then
		send_keys=false
	fi

	checkSession "$session"

	ftmux -n "$session" "code" "$repo"
	ftmux -w "$session" "run" -c "$repo/proj-jesse-ai-agent"

	# admin
	firstWindow=$(ftmux --session-win-id "$session" 0)
	firstPane=$(ftmux --window-pane-id "$firstWindow" 0)
	if [[ $send_keys == true ]]; then
		ftmux --send-keys "$firstPane" "source proj-jesse-ai-agent/env/bin/activate" "C-m" "rvim" "C-m"
	fi

	secondWindow=$(ftmux --session-win-id "$session" 1)
	firstPane=$(ftmux --window-pane-id "$secondWindow" 0)
	ftmux --split-pane -v -c "$WORKSPACE/rgt/jesse/chroma" -t "$firstPane"
	ftmux --split-pane -h -c "$WORKSPACE/rgt/jesse/special-project/client" -t "$firstPane"
	secondPane=$(ftmux --window-pane-id "$secondWindow" 1)
	thirdPane=$(ftmux --window-pane-id "$secondWindow" 2)
	ftmux --split-pane -h -c "$WORKSPACE/rgt/jesse/special-project/server" -t "$thirdPane"
	fourthPane=$(ftmux --window-pane-id "$secondWindow" 3)
	if [[ $send_keys == true ]]; then
		# ftmux --send-keys "$firstPane" "source env/bin/activate" "C-m" "python api/main.py" "C-m"
		ftmux --send-keys "$secondPane" "npm start" "C-m"
		# ftmux --send-keys "$thirdPane" "source env/bin/activate" "C-m" "docker-compose up --build" "C-m"
		ftmux --send-keys "$fourthPane" "source env/bin/activate" "C-m" "uvicorn api.main:app --reload" "C-m"
	fi

}
