#!/bin/zsh

# Do a Git clone
function clone() {
  git clone "$@"
}

# Do a Git commit
function quickie() {
  git add .;git add -u :/;git commit -m "$@";
}

function quickpush() {
  git add .
  git commit -m "$@"
  echo "🍏 commit message: [$@]"
  git push
  echo 🚀  quick push success... or not.
}

# Do a Git push from the current branch
function push() {
  git push origin "$@"
}

# Do a Git push setting the upstream from your current branch
function gpuo() {
  git push --set-upstream origin "$@"
}

# Do a Git commit/push
function gcap() {
  git add .;git add -u :/;git commit -m "$@";git push
}


