# Custom bookmarks
[[mgr.prepend_keymap]]
on   = [ "g", "b" ]
run  = "cd ~/.local/bin"
desc = "Cd to ~/.local/bin"

[[mgr.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Pictures"
desc = "Cd to ~/Pictures"

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd ~/Sync"
desc = "Cd to ~/Sync"

[[mgr.prepend_keymap]]
on   = [ "g", "w" ]
run  = "cd ~/personal/workspace"
desc = "Cd to ~/personal/workspace"

# Plugin keymaps
[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "T"
run = "plugin max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on = "H"
run = "plugin duckdb -1"
desc = "Scroll one column to the left"

[[mgr.prepend_keymap]]
on = "L"
run = "plugin duckdb +1"
desc = "Scroll one column to the right"

[[mgr.prepend_keymap]]
on = ["g", "o"]
run = "plugin duckdb -open"
desc = "open with duckdb"

[[mgr.prepend_keymap]]
on = ["g", "u"]
run = "plugin duckdb -ui"
desc = "open with duckdb ui"
