[manager]
ratio         = [ 1, 2, 3 ]
sort_by        = "alphabetical"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
show_hidden    = true
show_symlink   = true

[preview]
tab_size   = 2
max_width  = 600
max_height = 900
cache_dir  = ""

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
pdf = [
	{ run = 'zathura "$@"', orphan = true, for = "unix" },
]
image = [
	{ run = 'sxiv "$@" &', orphan = true, for = "unix" },
]
explorer = [
	{ run = 'thunar "$@" &', orphan = true, for = "unix" },
]
fallback = [
	{ run = 'xdg-open "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "play" },
	{ mime = "audio/*", use = "play" },
	{ mime = "inode/x-empty", use = "edit" },

	{ mime = "application/json", use = "edit" },
	{ mime = "*/javascript", use = "edit" },

	{ mime = "application/zip", use = "explorer" },
	{ mime = "application/gzip", use = "explorer" },
	{ mime = "application/x-tar", use = "explorer" },
	{ mime = "application/x-bzip", use = "explorer" },
	{ mime = "application/x-bzip2", use = "explorer" },
	{ mime = "application/x-7z-compressed", use = "explorer" },
	{ mime = "application/x-rar", use = "explorer" },

	{ mime = "application/pdf", use = "pdf" },

	{ mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false
