#!/bin/zsh

# alias -s {js,html,js,ts,css,md,lua,sh,conf}=$TEXT_EDITOR

safe_alias() {
  lhs=$1
  rhs=$2
  cmd=$3
  if [[ $+commands["$cmd"] ]]; then
    if [ -z "$rhs" ]; then
      alias "$lhs"="$cmd"
    else
      alias "$lhs"="$rhs"
    fi
  fi
}

safe_alias rv rvim
safe_alias pv pvim
safe_alias rvlog rvimProfiling
safe_alias nvlog nvimProfiling
safe_alias cm connmanctl
safe_alias py python
safe_alias xi tuxi
safe_alias ew toilet
safe_alias vsc "vscodium ." vscodium
safe_alias wl 'iwctl station list' iwctl
alias vm="rvim -no-cmp"
alias vc="rvim -no-min"
alias vts="rvim -no-min -ts"
alias vai="rvim -no-min -ts --ai"
alias vl="rvim -no-min -ts --lsp"
alias v="rvim -no-min -ts --lsp --ai"
alias vn="rvim -nice"
alias vL="rvim leetcode.nvim"
alias vd="rvim --neovide"
alias nn="NVIM_APPNAME=nativevim nvim"

alias onv="nvim_oldfiles"
alias orv="rvim_oldfiles"

if [[ $+commands[eza] ]]; then
  alias ls='eza --icons'
  alias ll="eza --long --all --git --color=always --group-directories-first --icons"
  alias lt="eza --icons --all --color=always -T"
else
  alias ls='ls --color=auto'
  alias l='ls -lFh'     # size,show type,human readable
  alias l.="ls -A | egrep '^\.'"
fi
alias ...="cd ../../.."
alias ....="cd ../../../.."
alias ipadd="curl icanhazip.com/"

# shell
alias b="bash"
alias d="dirs -v"
for index ({1..17}) alias "$index"="cd +${index}"; unset index
alias so="source"
alias cl='clear'
alias wd="pwd"
alias cdd="cd -"
alias zs='source $HOME/.config/zsh/.zshrc'
alias e="touch"
alias mk="mkdir"
alias loc="locate"
alias cmd='command -V'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'
alias rm='rm -i'
alias rmf='rm -f'
alias ccat='cat'

# system
alias obd="objdump -d"
alias wsc="iwlist scanning"
alias iws="sudo vi /etc/wpa_supplicant/wpa_supplicant.conf"
alias cswap="cat /proc/sys/vm/swappiness"
alias swap="sudo sysctl vm.swappiness=95"
alias brx='xrandr --output eDP --brightness'
alias br='brightnessctl -'
# easier to read disk
alias df='df -h'
alias free='free -m'
# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'
# get top process eating cpu
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
# get packages taking most space
alias bigg="expac -H M '%m\t%n' | sort -h | nl"
#Recent Installed Packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias riplong="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -3000 | nl"
#check vulnerabilities microcode
alias microcode='grep . /sys/devices/system/cpu/vulnerabilities/*'
#hardware info --short
alias hw="hwinfo --short"
#switch between bash and zsh
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"
alias ulist="cut -d: -f1 /etc/passwd"
#merge new settings
alias merge="xrdb -merge ~/.Xresources"
alias rec="ffmpeg -f x11grab -r 30 -s 1366x768 -i :0.0 $HOME/Recordings/$(date +%F_%H%M%S_%N).mp4"

#youtube-dl
alias yta-aac="youtube-dl --extract-audio --audio-format aac "
alias yta-best="youtube-dl --extract-audio --audio-format best "
alias yta-flac="youtube-dl --extract-audio --audio-format flac "
alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
alias yta-opus="youtube-dl --extract-audio --audio-format opus "
alias yta-vorbis="youtube-dl --extract-audio --audio-format vorbis "
alias yta-wav="youtube-dl --extract-audio --audio-format wav "
alias ytv-best="youtube-dl -f bestvideo+bestaudio "

# sudo
alias i='sudo'
alias ir='sudo rm -r'
alias ic="sudo cp -r"
alias im="sudo mv"
if [[ $+commands[sudoedit] ]]; then
  alias ie='sudoedit'
else
  alias ie='sudo vi'
fi
alias iv='sudo -v'
alias imi="sudo make install"
alias imci="sudo make install && sudo make clean install"
alias crole='sudo -iu'
alias uadd='sudo usermod -aG'

# Pacman
alias Qi="pacman -Qi"
alias Ql="pacman -Ql"
alias wp='pacman -Qs'
alias pac='sudo pacman -S'
alias rpac='sudo pacman -Rs'
alias Rpac='sudo pacman -Rcns'
alias U='sudo pacman -Qdtq'
alias upd="sudo pacman -Syu --noconfirm --overwrite '*'"
alias rcache="sudo pacman -Sc"
alias pkgs="pacman -Q | fzf"
alias p='paru -S'

pov () {
  pacman -S "$1" --noconfirm --overwrite '*'
}

#maintenance
alias clean='sudo pacman -Rns $(pacman -Qtdq)'
# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# sysact
alias sx="startx"
alias kx="killall xinit"
alias reb="sudo -A openrc-shutdown -rq now"
alias die="sudo -A openrc-shutdown -pq now"

# Programs
alias grep="grep --color=auto"
alias iredis="sudo /etc/init.d/redis_6379 start"
alias codium="sudo vi /usr/share/vscodium-bin/resources/app/product.json"
alias gvm="$GOPATH/bin/g"; # g-install: do NOT edit, see https://github.com/stefanmaric/g

# editor
alias a="$TEXT_EDITOR $HOME/.config/zsh/modules/aliases"
alias icl="$TEXT_EDITOR $HOME/.dots/clip/clip_hist.txt"
alias nvc="$TEXT_EDITOR config.h"
alias ivc="sudo vi /etc/xdg/nvim/sysinit.vim"
alias al="$TEXT_EDITOR $HOME/.config/alacritty/alacritty.toml"
alias zc="$TEXT_EDITOR $HOME/.config/zsh/.zshrc"
alias zcdd="rm $HOME/.cache/zsh/zcompdump"
alias ze="$TEXT_EDITOR $HOME/.config/zsh/.zshenv"
alias zp="$TEXT_EDITOR $HOME/.config/shell/profile"
alias xp="$TEXT_EDITOR $HOME/.config/x11/xprofile"
alias xc="$TEXT_EDITOR $HOME/.config/tmux/tmux.conf"
alias yc="$TEXT_EDITOR $HOME/.config/yazi/yazi.toml"
alias kc="$TEXT_EDITOR $HOME/.config/kitty/kitty.conf"
alias wzc="$TEXT_EDITOR $HOME/.config/wezterm/wezterm.lua"
alias alc="$TEXT_EDITOR $HOME/.config/alacritty/alacritty.yml"
alias xr="$TEXT_EDITOR $HOME/.config/x11/xresources"
alias xR="$TEXT_EDITOR $HOME/.Xresources"
alias xn="$TEXT_EDITOR $HOME/.config/x11/xinitrc"
alias nvi="$TEXT_EDITOR init.lua"
alias rvi="$TEXT_EDITOR init.lua"
alias h="$TEXT_EDITOR $HOME/.cache/zsh/.zsh_history"
alias rvz="$TEXT_EDITOR $HOME/.zsh_history"
alias sec="$TEXT_EDITOR $HOME/.dots/sensitive/secrets"
alias clip="$TEXT_EDITOR $HOME/.dots/clip/clip_hist.txt"
alias links="$TEXT_EDITOR $HOME/Sync/Android/MacroDroid/Links.txt"

# Docker and Docker Compose
# alias idocker="systemctl start docker.service"
alias udocker="sudo rc-update add docker default"
# alias udocker="sudo rc-update del docker default"
alias idocker="sudo rc-service docker start"
alias dc="docker-compose"
alias dce="docker-compose exec"
alias dci="docker-compose up"
alias dcd="docker-compose down -v"
alias juiceshop='docker run --rm -p 3000:3000 bkimminich/juice-shop'
alias swagger='docker run --rm -it  --user $(id -u):$(id -g) -e GOPATH=$(go env GOPATH):/go -v $HOME:$HOME -w "$(pwd)" quay.io/goswagger/swagger'

# git
alias gcma="git commit -a -v"

# git bare (nvim, dotfiles)
alias conf='/usr/bin/git --git-dir=$HOME/.dots/dotfiles/ --work-tree=$HOME'
alias ca="cconf -csa"
alias ccms="cconf -ccoms"
alias ccm="cconf -ccom"
alias ccma="cconf -ccma"
alias ccm="cconf -ccomall"
alias cpl="cconf -ce"
alias cps="cconf -cp"
alias cst="cconf -cs"
alias cstb="conf status -sb"
alias ccv="conf commit -v"
alias cadd="conf add"

# ranger
alias rr="ranger"
alias f='yazi'
alias yz='yazi'

# tmux
alias xsp="tmux display -p '#{socket_path}'"
alias xls="tmux ls"
alias fx="ftmux"
alias fn="ftmux -n"
alias fk="ftmux -kp"
alias fkk="ftmux -k"
alias fs="ftmux -s"
alias dm='dmenumount'
alias du='dmenuumount'

alias ywa="yarn watch"
alias esft="eslint_d --fix"
alias npmrf="npm run format"
alias npmrl="npm run lint"
alias npmrb="npm run build"
alias pf="prettier --write"
alias clocc="cloc . --exclude-dir=node_modules,.next,dist,.turbo,.git --exclude-ext=yaml,json,svg"

# Misc
alias rustbook='rustup docs --book'
alias rfonts='fc-cache -vf ~/.local/share/fonts/'
alias plague='curl https://corona-stats.online/states/us'
alias lg='lazygit'
alias aria='aria2c --max-connection-per-server=12'
alias cf="find -type f | sed 's/^..//g' | fzf | tr -d '\n' | xclip -sel c"
alias cff="find | fzf | sed 's/^..//g' | tr -d '\n' | xclip -sel c"
alias thequickbrownfoxjumpsoverthelazydog="echo hellooooo"
alias reld="reload_drivers"
alias zin="zen_installer"
alias zdel="zen_del"
alias zup="zen_update"
alias wf="wifi_toggle"
alias uv="uvicorn api.main:app"
alias uvr="uvicorn api.main:app --reload"
alias tp="tmux-project"

ws=~/personal/workspace
vt=/run/media/razak/Ventoy
usb=/run/media/razak/E48F-B0EB

alias nca='cd "$XDG_CACHE_HOME/nvim"'
alias rca='cd "$XDG_CACHE_HOME/rvim"'
alias nsh='cd "$XDG_DATA_HOME/nvim"'
alias rsh='cd "$XDG_DATA_HOME/rvim"'
alias co='cd "$XDG_CONFIG_HOME"'
alias cdnv='cd "$XDG_CONFIG_HOME/nvim"'
alias cdrv='cd "$XDG_CONFIG_HOME/rvim"'
alias cdco='cd "$XDG_CONFIG_HOME"'
alias cdmo='cd "$HOME/.mozilla/firefox/profiles"'
alias dw='cd "$HOME/Downloads"'
alias dnv='cd "$HOME/.dots/nvim"'
alias vids='cd "$HOME/Videos"'
alias ws='cd "$ws"'
alias usb='cd "$usb"'
alias vt='cd "$vt"'
alias cdcc='cd "$ws/coding"'
alias notes='cd "$HOME/notes"'
