#!/bin/zsh

alias v="$EDITOR ./"
alias -s {js,html,js,ts,css,md,lua,sh,conf}=$TEXT_EDITOR

safe_alias() {
  lhs=$1
  rhs=$2
  cmd=$3
  if [[ $+commands["$cmd"] ]]; then
    if [ -z "$rhs" ]; then
      alias "$lhs"="$cmd"
    else
      alias "$lhs"="$rhs"
    fi
  fi
}

safe_alias rv rvim
safe_alias pv pvim
safe_alias rvlog rvimProfiling
safe_alias nvlog nvimProfiling
safe_alias cm connmanctl
safe_alias py python
safe_alias xi tuxi
safe_alias ew toilet
safe_alias vsc "vscodium ." vscodium
safe_alias wl 'iwctl station list' iwctl

if [[ $+commands[exa] ]]; then
  alias ls='exa'
  alias ll="exa --long --all --git --color=always --group-directories-first --icons $@"
  alias lt="exa --icons --all --color=always -T $@"
else
  alias ls='ls --color=auto'
  alias l='ls -lFh'     # size,show type,human readable
  alias l.="ls -A | egrep '^\.'"
fi
alias ...="cd ../../.."
alias ....="cd ../../../.."
alias ipadd="curl icanhazip.com/"

# shell
alias b="bash"
alias d="dirs -v"
for index ({1..17}) alias "$index"="cd +${index}"; unset index
alias so="source"
alias cl='clear'
alias wd="pwd"
alias cdd="cd -"
alias zs='source $HOME/.config/zsh/.zshrc'
alias e="touch"
alias m="mkdir"
alias loc="locate"
alias cmd='command -V'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'
alias rm='rm -i'
alias rmf='rm -f'
alias ccat='cat'
alias notes='fn'

# system
alias obd="objdump -d"
alias wsc="iwlist scanning"
alias iws="sudo vi /etc/wpa_supplicant/wpa_supplicant.conf"
alias swap="cat /proc/sys/vm/swappiness"
alias brx='xrandr --output eDP-1 --brightness'
alias br='brightnessctl -'
# easier to read disk
alias df='df -h'
alias free='free -m'
# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'
# get top process eating cpu
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
# get packages taking most space
alias bigg="expac -H M '%m\t%n' | sort -h | nl"
#Recent Installed Packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias riplong="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -3000 | nl"
#check vulnerabilities microcode
alias microcode='grep . /sys/devices/system/cpu/vulnerabilities/*'
#hardware info --short
alias hw="hwinfo --short"
#switch between bash and zsh
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"
alias ulist="cut -d: -f1 /etc/passwd"
#merge new settings
alias merge="xrdb -merge ~/.Xresources"

#youtube-dl
alias yta-aac="youtube-dl --extract-audio --audio-format aac "
alias yta-best="youtube-dl --extract-audio --audio-format best "
alias yta-flac="youtube-dl --extract-audio --audio-format flac "
alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
alias yta-opus="youtube-dl --extract-audio --audio-format opus "
alias yta-vorbis="youtube-dl --extract-audio --audio-format vorbis "
alias yta-wav="youtube-dl --extract-audio --audio-format wav "
alias ytv-best="youtube-dl -f bestvideo+bestaudio "

# sudo
alias i='sudo'
alias ir='sudo rm -r'
alias ic="sudo cp -r"
alias im="sudo mv"
alias ie='sudo vi'
alias iv='sudo -v'
alias imi="sudo make install"
alias imci="sudo make clean install"
alias crole='sudo -iu'
alias uadd='sudo usermod -aG'

# Pacman
alias Qi="pacman -Qi"
alias Ql="pacman -Ql"
alias wp='pacman -Qs'
alias pac='sudo pacman -S'
alias r='sudo pacman -Rs'
alias R='sudo pacman -Rcns'
alias U='sudo pacman -Qdtq'
alias upd='sudo pacman -Syu'
alias rcache="sudo pacman -Sc"
alias pkgs="pacman -Q | fzf"
alias p='paru -S'
#maintenance
alias clean='sudo pacman -Rns $(pacman -Qtdq)'
# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# sysact
alias sx="startx"
alias kx="killall xinit"
alias reb="sudo -A openrc-shutdown -rq now"
alias die="sudo -A openrc-shutdown -pq now"

# Programs
alias grep="grep --color=auto"
alias iredis="sudo /etc/init.d/redis_6379 start"
alias codium="sudo vi /usr/share/vscodium-bin/resources/app/product.json"

# editor
alias a="$TEXT_EDITOR $HOME/.config/zsh/modules/aliases"
alias icl="$TEXT_EDITOR $HOME/.dots/clip/clip_hist.txt"
alias lc='rv ${RVIM_CONFIG_PATH:-$HOME/.config}/rvim/lua/user/config/init.lua'
alias rvc='rv ${RVIM_CONFIG_PATH:-$HOME/.config}/rvim/init.lua'
alias nvc="$TEXT_EDITOR config.h"
alias ivc="sudo vi /etc/xdg/nvim/sysinit.vim"
alias al="$TEXT_EDITOR $HOME/.config/alacritty/alacritty.yml"
alias zc="$TEXT_EDITOR $HOME/.config/zsh/.zshrc"
alias ze="$TEXT_EDITOR $HOME/.config/zsh/.zshenv"
alias zp="$TEXT_EDITOR $HOME/.config/shell/profile"
alias xp="$TEXT_EDITOR $HOME/.config/x11/xprofile"
alias xc="$TEXT_EDITOR $HOME/.config/tmux/tmux.conf"
alias xr="$TEXT_EDITOR $HOME/.config/x11/xresources"
alias xR="$TEXT_EDITOR $HOME/.Xresources"
alias xn="$TEXT_EDITOR $HOME/.config/x11/xinitrc"
alias nvi="rv init.lua"
alias rvi="rv init.lua"
alias nvz="$TEXT_EDITOR $HOME/.cache/zsh/.zsh_history"
alias rvz="$TEXT_EDITOR $HOME/.zsh_history"

# Docker and Docker Compose
# alias idocker="systemctl start docker.service"
alias udocker="sudo rc-update add docker default"
# alias udocker="sudo rc-update del docker default"
alias idocker="sudo rc-service docker start"
alias dc="docker-compose"
alias dce="docker-compose exec"
alias dci="docker-compose up"
alias dcd="docker-compose down -v"
alias juiceshop='docker run --rm -p 3000:3000 bkimminich/juice-shop'

# git bare (nvim, dotfiles)
alias conf='/usr/bin/git --git-dir=$HOME/.dots/dotfiles/ --work-tree=$HOME'
alias ca="iconf -csa"
alias ccms="iconf -ccoms"
alias ccm="iconf -ccom"
alias ccma="iconf -ccma"
alias ccm="iconf -ccomall"
alias cpl="iconf -ce"
alias cps="iconf -cp"
alias cst="iconf -cs"
alias cstb="conf status -sb"

# ranger
alias f="ranger"
alias rc='ranger $HOME/.config'
alias rnv='ranger $HOME/.config/nvim'

# tmux
alias xd="tmuxd first"
alias xb="tmuxb first"
alias xsp="tmux display -p '#{socket_path}'"
alias xls="tmux ls"
alias ftn='ftmux -s'
alias ftk='ftmux -k'
alias dm='dmenumount'
alias du='dmenuumount'

alias ywa="yarn watch"

# Misc
alias rustbook='rustup docs --book'
alias rfonts='fc-cache -vf ~/.local/share/fonts/'
alias plague='curl https://corona-stats.online/states/us'
alias lg='lazygit'
alias aria='aria2c --max-connection-per-server=12'
alias cf="find -type f | sed 's/^..//g' | fzf | tr -d '\n' | xclip -sel c"
alias cff="find | fzf | sed 's/^..//g' | tr -d '\n' | xclip -sel c"
alias thequickbrownfoxjumpsoverthelazydog="echo hellooooo"

mo=~/.mozilla/firefox/profiles
rca=~/.cache/rvim
doc=~/Documents
docs=~/docs
dots=~/.dots
dw=~/Downloads
co=~/.config

alias nca='cd "$rca"'
alias dw='cd "$dw"'
alias co='cd "$XDG_CONFIG_HOME"'
alias nsh='cd "$XDG_DATA_HOME/rvim"'
alias rsh='cd "$XDG_DATA_HOME/rvim"'
alias cdc='cd "$doc"'
alias cdco='cd "$co"'
alias cdmo='cd "$mo"'
alias cdcs='cd "$docs"'
alias ws='cd "$HOME/personal/workspace"'
alias cdcc='cd "$HOME/personal/workspace/coding"'
alias cdnv='cd "$XDG_CONFIG_HOME/nvim"'
alias cdrv='cd "$XDG_CONFIG_HOME/rvim"'
