#!/bin/zsh

#-------------------------------------------------------------------------------
#               Completion
#-------------------------------------------------------------------------------
typeset -A __DOTS

__DOTS[ITALIC_ON]=$'\e[3m'
__DOTS[ITALIC_OFF]=$'\e[23m'

# Init completions
autoload -Uz compinit
zmodload -i zsh/complist

# Load and initialize the completion system ignoring insecure directories with a
# cache time of 20 hours, so it should almost always regenerate the first time a
# shell is opened each day.
# #q expands globs in conditional expressions
_comp_path="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
if [[ $_comp_path(#qNmh-20) ]]; then
  # -C (skip function check) implies -i (skip security check).
  compinit -C -d "$_comp_path"
else
  mkdir -p "$_comp_path:h"
  compinit -i -d "$_comp_path"
  # Keep $_comp_path younger than cache time even if it isn't regenerated.
  touch "$_comp_path"
fi
unset _comp_path

#-------------------------------------------------------------------------------
#               Styling & Stuff
#-------------------------------------------------------------------------------
# Enable keyboard navigation of completions in menu
# (not just tab/shift-tab but cursor keys as well):
zstyle ':completion:*:*:*:*:*' menu select

# Make completion:
# (stolen from Wincent)
# - Try exact (case-sensitive) match first.
# - Then fall back to case-insensitive.
# - Accept abbreviations after . or _ or - (ie. f.b -> foo.bar).
# - Substring complete (ie. bar -> foobar).
zstyle ':completion:*' matcher-list '' '+m:{[:lower:]}={[:upper:]}' '+m:{[:upper:]}={[:lower:]}' '+m:{_-}={-_}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# Allow completion of ..<Tab> to ../ and beyond.
zstyle -e ':completion:*' special-dirs '[[ $PREFIX = (../)#(..) ]] && reply=(..)'

# Colorize completions using  `ls` colors.
zstyle ':completion:*' list-colors ''
# zstyle ':completion:*' list-colors ${(s.:.)__DOTS[LS_COLORS]}

# Only display some tags for the command cd
zstyle ':completion:*:*:cd:*' tag-order local-directories directory-stack path-directories

# Use caching to make completion for commands such as dpkg and apt usable.
zstyle ':completion::complete:*' use-cache on
zstyle ':completion:*' cache-path "$ZSH_CACHE_DIR/zcompcache"

# Group matches and descriptions.
zstyle ':completion:*:*:*:*:corrections' format '%F{teal}!- %d (errors: %e) -!%f'
zstyle ':completion:*:*:*:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:*:*:*:warnings' format ' %F{red}-- no matches found --%f'
# zstyle ':completion:*:*:*:*:descriptions' format %F{#7685b1}%B%U%{$__DOTS[ITALIC_ON]%}%d%{$__DOTS[ITALIC_OFF]%}%b%u%f
# zstyle ':completion:*:*:*:*:descriptions' format ' %F{blue}-- %d --%f'

# enabling autocompletion in privileged environments.
zstyle ':completion::complete:*' gain-privileges 1

# Required for completion to be in groups (named after the tags)
zstyle ':completion:*' group-name ''
zstyle ':completion:*:*:-command-:*:*' group-order commands alias functions builtins

# force zsh to realize new commands
zstyle ':completion:*' completer _oldlist _expand _complete _match _prefix _ignored _approximate

# This enables Zsh to understand commands like docker run -it ubuntu.
# However, by enabling this, this also makes Zsh complete docker run
# -u<tab> with docker run -uapprox which is not valid. The users have
# to put the space or the equal sign themselves before trying to complete.
# Therefore, this behavior is disabled by default. To enable it:
zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

# Added by running `compinstall`
zstyle ':completion:*' expand suffix
zstyle ':completion:*:default' list-prompt '%S%M matches%s'
# zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' list-suffixes true
# End of lines added by compinstall

# Detaled list of files and folders
# zstyle ':completion:*' file-list all

# Expand // to /
zstyle ':completion:*' squeeze-slashes true

# Order completions by date of modification.
zstyle ':completion:*' file-sort modification

# Suggest options like "-L, -f" after - for commands like cd chdir on tab.
zstyle ':completion:*' complete-options true

# Here, with vim, ignore .(aux|log|pdf) files
zstyle ':completion:*:*:nvim:*' file-patterns '^*.(aux|log|pdf):source-files' '*:all-files'
zstyle ':completion:*:*:rvim:*' file-patterns '^*.(aux|log|pdf):source-files' '*:all-files'

zstyle ':hist:*' expand-aliases no

#-------------------------------------------------------------------------------
#   CDR
#-------------------------------------------------------------------------------
# https://github.com/zsh-users/zsh/blob/master/Functions/Chpwd/cdr

zstyle ':completion:*:*:cdr:*:*' menu selection
# $WINDOWID is an environment variable set by kitty representing the window ID
# of the OS window (NOTE this is not the same as the $KITTY_WINDOW_ID)
# @see: https://github.com/kovidgoyal/kitty/pull/2877
zstyle ':chpwd:*' recent-dirs-file $ZSH_CACHE_DIR/.chpwd-recent-dirs-${WINDOWID##*/} +
zstyle ':completion:*' recent-dirs-insert always
zstyle ':chpwd:*' recent-dirs-default yes
