#!/bin/zsh

autoload -Uz add-zsh-hook

zshcache_time="$(date +%s%N)"

function __auto-ls-after-cd() {
  emulate -L zsh
  # Only in response to a user-initiated `cd`, not indirectly (eg. via another
  # function).
  if [ "$ZSH_EVAL_CONTEXT" = "toplevel:shfunc" ]; then
    ls -a
  fi
}

# On-demand rehash
rehash_precmd() {
  if [[ -a /var/cache/zsh/pacman ]]; then
    local paccache_time="$(date -r /var/cache/zsh/pacman +%s%N)"
    if (( zshcache_time < paccache_time )); then
      rehash
      zshcache_time="$paccache_time"
    fi
  fi
}

add-zsh-hook -Uz precmd rehash_precmd

reset_broken_terminal () {
  printf '%b' '\e[0m\e(B\e)0\017\e[?5l\e7\e[0;0r\e8'
}
add-zsh-hook -Uz precmd reset_broken_terminal

command_not_found_handler() {
  local pkgs cmd="$1" files=()
  printf 'command not found: %s\n' "$cmd" # print command not found asap, then search for packages
  return 127
}

add-zsh-hook chpwd () {
  __auto-ls-after-cd
}
