#!/bin/zsh

#-------------------------------------------------------------------------------
#               Vi-mode
#-------------------------------------------------------------------------------

bindkey -v   # bindkey -e will be emacs mode
export KEYTIMEOUT=1

# Change cursor shape for different vi modes.
function zle-keymap-select () {
  case $KEYMAP in
    vicmd) echo -ne '\e[1';;      # block
    viins|main) echo -ne '\e[5';; # beam
  esac
}

# solid cursor noblinking for all modes
function zle-keymap-block () {
  echo -e '\e[?17;14;224c'
}

zle -N zle-keymap-block

# echo -ne '\e[5 q' # Use beam shape cursor on startup.
# preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'n' vi-down-line-or-history
